/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Question as PrismaQuestion,
  UserPerformance as PrismaUserPerformance,
  ExamBoard as PrismaExamBoard,
  Topic as PrismaTopic,
} from "@prisma/client";

export class QuestionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.QuestionCountArgs, "select">): Promise<number> {
    return this.prisma.question.count(args);
  }

  async questions(
    args: Prisma.QuestionFindManyArgs
  ): Promise<PrismaQuestion[]> {
    return this.prisma.question.findMany(args);
  }
  async question(
    args: Prisma.QuestionFindUniqueArgs
  ): Promise<PrismaQuestion | null> {
    return this.prisma.question.findUnique(args);
  }
  async createQuestion(
    args: Prisma.QuestionCreateArgs
  ): Promise<PrismaQuestion> {
    return this.prisma.question.create(args);
  }
  async updateQuestion(
    args: Prisma.QuestionUpdateArgs
  ): Promise<PrismaQuestion> {
    return this.prisma.question.update(args);
  }
  async deleteQuestion(
    args: Prisma.QuestionDeleteArgs
  ): Promise<PrismaQuestion> {
    return this.prisma.question.delete(args);
  }

  async findUserPerformances(
    parentId: string,
    args: Prisma.UserPerformanceFindManyArgs
  ): Promise<PrismaUserPerformance[]> {
    return this.prisma.question
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .userPerformances(args);
  }

  async getExamBoard(parentId: string): Promise<PrismaExamBoard | null> {
    return this.prisma.question
      .findUnique({
        where: { id: parentId },
      })
      .examBoard();
  }

  async getTopic(parentId: string): Promise<PrismaTopic | null> {
    return this.prisma.question
      .findUnique({
        where: { id: parentId },
      })
      .topic();
  }
}
